# Training a Single Neuron 

In [1]:
import pandas as pd
import numpy as np

In [2]:
import seaborn as sb

In [3]:
df = pd.read_csv("realestate.csv")

In [4]:
df.head()

area  rooms  floor  elev  parking    price
0   232     11     12     0        2  2616000
1   249     11      5     1        2  2917000
2   225     10     12     1        2  2698000
3    51      2      7     0        2   784000
4   192      9      3     0        0  2075000

In [5]:
print(df.price.min())
print(df.price.max())

330000
3170000


In [6]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [7]:
def sigmoid_der(x):
    return x*(1-x)

In [8]:
def train_NN(x,y):
    weights = np.arange(x.shape[1],dtype=np.float)
    weights.fill(0.1)
    weights = weights.reshape(x.shape[1],1)
    
    for iter in range(100000):
        l1 = sigmoid(np.dot(x,weights))
        err = y - l1
        delta = err * sigmoid_der(l1)
        weights += np.dot(x.T,delta)
        
    return weights

In [9]:
def predict(vals,weights):
    return sigmoid(np.dot(vals,weights))

Use MinMaxScalar to transform the dataframe

In [10]:
from sklearn.preprocessing import MinMaxScaler
sc =  MinMaxScaler()

In [11]:
df2 = sc.fit_transform(df)

In [12]:
df2 = pd.DataFrame(df2, columns=df.columns)
df2

area     rooms     floor  elev  parking     price
0     0.872727  0.909091  1.000000   0.0      1.0  0.804930
1     0.950000  0.909091  0.363636   1.0      1.0  0.910915
2     0.840909  0.818182  1.000000   1.0      1.0  0.833803
3     0.050000  0.090909  0.545455   0.0      1.0  0.159859
4     0.690909  0.727273  0.181818   0.0      0.0  0.614437
...        ...       ...       ...   ...      ...       ...
4995  0.413636  0.454545  0.000000   1.0      1.0  0.514085
4996  0.372727  0.363636  1.000000   0.0      1.0  0.379225
4997  0.022727  0.000000  0.454545   0.0      0.0  0.051761
4998  0.354545  0.363636  0.272727   1.0      0.5  0.410915
4999  0.836364  0.818182  0.000000   0.0      1.0  0.798944

[5000 rows x 6 columns]

In [13]:
df = df2

Split the dataframe to numpy arrays (X,Y) <br>
Take only 20 rows

In [14]:
x = df.drop(['price'], axis=1).values[ :20, :]
x

array([[0.87272727, 0.90909091, 1.        , 0.        , 1.        ],
       [0.95      , 0.90909091, 0.36363636, 1.        , 1.        ],
       [0.84090909, 0.81818182, 1.        , 1.        , 1.        ],
       [0.05      , 0.09090909, 0.54545455, 0.        , 1.        ],
       [0.69090909, 0.72727273, 0.18181818, 0.        , 0.        ],
       [0.54090909, 0.54545455, 0.81818182, 1.        , 0.5       ],
       [0.99545455, 1.        , 0.36363636, 0.        , 0.5       ],
       [0.27272727, 0.27272727, 0.90909091, 0.        , 1.        ],
       [0.30454545, 0.27272727, 0.72727273, 0.        , 1.        ],
       [0.68636364, 0.72727273, 0.54545455, 0.        , 0.        ],
       [0.25454545, 0.27272727, 0.54545455, 1.        , 1.        ],
       [0.27727273, 0.27272727, 0.36363636, 0.        , 0.5       ],
       [0.45909091, 0.45454545, 0.63636364, 1.        , 0.5       ],
       [0.40454545, 0.36363636, 0.81818182, 0.        , 0.5       ],
       [0.07272727, 0.09090909, 0.

In [15]:
y = df['price'].values[ :20]
y

array([0.80492958, 0.91091549, 0.83380282, 0.15985915, 0.61443662,
       0.57535211, 0.84225352, 0.30669014, 0.34964789, 0.56091549,
       0.36408451, 0.26443662, 0.49753521, 0.36619718, 0.11549296,
       0.29014085, 0.69929577, 0.23802817, 0.25774648, 0.53908451])

Train the network and check with predict the first 5 rows

In [16]:
w = train_NN(x,y.reshape(-1,1))

In [17]:
w

array([[ 7.75204246],
       [-5.02303405],
       [-1.47248902],
       [ 0.04116724],
       [-0.44794306]])

In [18]:
x1 = df.drop(['price'], axis=1).values[ :5, :]
x1

array([[0.87272727, 0.90909091, 1.        , 0.        , 1.        ],
       [0.95      , 0.90909091, 0.36363636, 1.        , 1.        ],
       [0.84090909, 0.81818182, 1.        , 1.        , 1.        ],
       [0.05      , 0.09090909, 0.54545455, 0.        , 1.        ],
       [0.69090909, 0.72727273, 0.18181818, 0.        , 0.        ]])

In [19]:
predict(x1, w)

array([[0.56920105],
       [0.86480892],
       [0.62942317],
       [0.2107923 ],
       [0.80769714]])

In [20]:
y1 = df['price'].values[ :5]
y1

array([0.80492958, 0.91091549, 0.83380282, 0.15985915, 0.61443662])

Add a bias column with constant value 1 and run the above again

In [21]:
df['bias']=1
df.head()

area     rooms     floor  elev  parking     price  bias
0  0.872727  0.909091  1.000000   0.0      1.0  0.804930     1
1  0.950000  0.909091  0.363636   1.0      1.0  0.910915     1
2  0.840909  0.818182  1.000000   1.0      1.0  0.833803     1
3  0.050000  0.090909  0.545455   0.0      1.0  0.159859     1
4  0.690909  0.727273  0.181818   0.0      0.0  0.614437     1

In [22]:
x = df.drop(['price'], axis=1).values[ :20, :]
x

array([[0.87272727, 0.90909091, 1.        , 0.        , 1.        ,
        1.        ],
       [0.95      , 0.90909091, 0.36363636, 1.        , 1.        ,
        1.        ],
       [0.84090909, 0.81818182, 1.        , 1.        , 1.        ,
        1.        ],
       [0.05      , 0.09090909, 0.54545455, 0.        , 1.        ,
        1.        ],
       [0.69090909, 0.72727273, 0.18181818, 0.        , 0.        ,
        1.        ],
       [0.54090909, 0.54545455, 0.81818182, 1.        , 0.5       ,
        1.        ],
       [0.99545455, 1.        , 0.36363636, 0.        , 0.5       ,
        1.        ],
       [0.27272727, 0.27272727, 0.90909091, 0.        , 1.        ,
        1.        ],
       [0.30454545, 0.27272727, 0.72727273, 0.        , 1.        ,
        1.        ],
       [0.68636364, 0.72727273, 0.54545455, 0.        , 0.        ,
        1.        ],
       [0.25454545, 0.27272727, 0.54545455, 1.        , 1.        ,
        1.        ],
       [0.27727273, 0

In [23]:
y = df['price'].values[ :20]
y

array([0.80492958, 0.91091549, 0.83380282, 0.15985915, 0.61443662,
       0.57535211, 0.84225352, 0.30669014, 0.34964789, 0.56091549,
       0.36408451, 0.26443662, 0.49753521, 0.36619718, 0.11549296,
       0.29014085, 0.69929577, 0.23802817, 0.25774648, 0.53908451])

In [24]:
w = train_NN(x,y.reshape(-1,1))

In [25]:
w

array([[ 4.03442213],
       [-0.28166808],
       [-0.11654035],
       [ 0.37937946],
       [ 0.42615909],
       [-2.18954246]])

In [26]:
x1 = df.drop(['price'], axis=1).values[ :5, :]
x1

array([[0.87272727, 0.90909091, 1.        , 0.        , 1.        ,
        1.        ],
       [0.95      , 0.90909091, 0.36363636, 1.        , 1.        ,
        1.        ],
       [0.84090909, 0.81818182, 1.        , 1.        , 1.        ,
        1.        ],
       [0.05      , 0.09090909, 0.54545455, 0.        , 1.        ,
        1.        ],
       [0.69090909, 0.72727273, 0.18181818, 0.        , 0.        ,
        1.        ]])

In [27]:
predict(x1, w)

array([[0.79978716],
       [0.89569278],
       [0.84045029],
       [0.16099601],
       [0.59190298]])

In [28]:
y1 = df['price'].values[ :5]
y1

array([0.80492958, 0.91091549, 0.83380282, 0.15985915, 0.61443662])

Change the training set size to 200 and run all again

In [29]:
x = df.drop(['price'], axis=1).values[ :200, :]
y = df['price'].values[ :200]
w = train_NN(x,y.reshape(-1,1))

In [30]:
w

array([[ 6.98976186],
       [ 4.58652231],
       [-0.70423316],
       [ 0.87050448],
       [ 0.8729733 ],
       [-8.56076463]])

Predict 10 rows (index 40 to 49) from the dataframe and check the result  

In [31]:
df['price'].values[40:50]

array([0.78697183, 0.11373239, 0.6943662 , 0.22112676, 0.73802817,
       0.75387324, 0.4834507 , 0.82359155, 0.9084507 , 0.52957746])

In [32]:
predict(df.drop(['price'], axis=1).values[40:50] , w )

array([[9.27418156e-01],
       [3.25501829e-04],
       [6.79380559e-01],
       [1.78158158e-03],
       [7.77043139e-01],
       [7.82742914e-01],
       [5.73612220e-02],
       [9.21549491e-01],
       [9.80306327e-01],
       [8.01747907e-02]])